# Node.js

# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master
  - develop
  - feature/*
  - release/*

pool:
  vmImage: 'ubuntu-latest'

steps:

  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Install Node.js'

  - script: yarn install
    displayName: 'Yarn install'

  - script: yarn lint
    displayName: 'Yarn Lint'

  - script: yarn build
    displayName: 'Yarn build'

 #   - script: yarn test
 #     displayName: 'Yarn test'
 #   - script: bash <(curl -s https://codecov.io/bash)
 #     displayName: 'Publish test results to Codecov'
 # 
 #   - task: PublishCodeCoverageResults@1
 #     displayName: 'Publish test coverage results'
 #     inputs:
 #       codeCoverageTool: Cobertura
 #       summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/*coverage.xml'
 #       reportDirectory: '$(System.DefaultWorkingDirectory)/coverage'
 # 
 #   - task: PublishTestResults@2
 #     displayName: Publish test results
 #     condition: succeededOrFailed()
 #     inputs:
 #       testRunner: JUnit
 #       testResultsFiles: '$(System.DefaultWorkingDirectory)/coverage/junit.xml'

  - script: yarn workspace @fury/frontend build
    displayName: 'Webpack build'

  - task: ArchiveFiles@1
    displayName: Compress frontend artifacts
    inputs:
      archiveFile: $(System.DefaultWorkingDirectory)/frontend.zip
      rootFolder: '$(System.DefaultWorkingDirectory)/frontend/bundle/assets'
      includeRootFolder: false

  - task: PublishBuildArtifacts@1
    displayName: Publish frontend bundle artifacts
    inputs:
      pathtoPublish: '$(System.DefaultWorkingDirectory)/frontend.zip'
      artifactName: frontend

  - script: rm -rf $(System.DefaultWorkingDirectory)/service/node_modules
    displayName: "Cleanup Service package"

  - task: ArchiveFiles@1
    displayName: Compress service artifacts
    inputs:
      archiveFile: $(System.DefaultWorkingDirectory)/service.zip
      rootFolder: $(System.DefaultWorkingDirectory)/service
      includeRootFolder: false

  - task: PublishBuildArtifacts@1
    displayName: Publish Backend Service artifacts
    inputs:
      pathtoPublish: '$(System.DefaultWorkingDirectory)/service.zip'
      artifactName: service

  